apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-w0uf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-w0uf
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-w0uf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-w0uf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-w0uf
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-brce-tenant/dotnet-component/devfile-sample-dotnet60-basic-w0uf@sha256:b416d1bed2a6c3102a031ac9b404fd054a13113e790e4b99e5a683a943f28607
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
